import { Inter } from "next/font/google";
import "./globals.css";
import NavBer from "@/Components/GlobalComponents/NavBer";
import Foot from "@/Components/GlobalComponents/Foot";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBer></NavBer>
      <div className='px-[5%]'>
            {children}
      </div>
    
      <Foot></Foot>
        </body>
    </html>
  );
}
